In [1]:
import pandas

#pandas.options.display.max_columns = None
#pandas.options.display.max_rows = None

tvshow = pandas.read_csv("tv_shows.csv")
tvshow

,Unnamed: 0,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type
0,0,1,Breaking Bad,2008,18+,9.4/10,100/100,1,0,0,0,1
1,1,2,Stranger Things,2016,16+,8.7/10,96/100,1,0,0,0,1
2,2,3,Attack on Titan,2013,18+,9.0/10,95/100,1,1,0,0,1
3,3,4,Better Call Saul,2015,18+,8.8/10,94/100,1,0,0,0,1
4,4,5,Dark,2017,16+,8.8/10,93/100,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5363,5363,5713,Paradise Islands,2017,NaN,NaN,10/100,0,0,0,1,1
5364,5364,5714,Mexico Untamed,2018,NaN,NaN,10/100,0,0,0,1,1
5365,5365,5715,Wild Centeral America,2020,NaN,NaN,10/100,0,0,0,1,1
5366,5366,5716,Wild Russia,2018,NaN,NaN,10/100,0,0,0,1,1
5367,5367,5717,Fearless Adventures with Jack Randall,2018,NaN,NaN,10/100,0,0,0,1,1

In [23]:
# Which streaming platform has the most shows?
netflix = tvshow[tvshow["Netflix"] == 1]
nshows = len(netflix)

hulu = tvshow[tvshow["Hulu"] == 1]
hshows = len(hulu)

primevideo = tvshow[tvshow["Prime Video"] == 1]
pshows = len(primevideo)

disney = tvshow[tvshow["Disney+"] == 1]
dshows = len(disney)

print("Netflix show count:", nshows,"\nHulu show count:", 
      hshows, "\nPrime Video show count:", pshows, "\nDisney+ show count:", dshows)

Netflix show count: 1971
Hulu show count: 1621
Prime Video show count: 1831
Disney+ show count: 351

# Here I was finding which streaming platform had the most tv shows across Netflix, Hulu, Prime Video, and Disney+. My findings show that Netflix had the most tv shows totalling at 1,971 with Prime Video at a close second with 1,831 shows on their platform. That being said Disney+ had the least amount of shows at 351.

In [26]:
# What is the average tv show year (year the tv show was produced) for each streaming platform?
netflix = tvshow[tvshow["Netflix"] == 1]
navg_year = netflix["Year"].mean()

hulu = tvshow[tvshow["Hulu"] == 1]
havg_year = hulu["Year"].mean()

primevideo = tvshow[tvshow["Prime Video"] == 1]
pavg_year = primevideo["Year"].mean()

disney = tvshow[tvshow["Disney+"] == 1]
davg_year = disney["Year"].mean()

print("Netflix's Average Show Year:", navg_year,"\nHulu's Average Show Year:", 
      havg_year, "\nPrime Video's Average Show Year:", pavg_year, "\nDisney+'s Average Show Year:", davg_year)

Netflix's Average Show Year: 2016.2836123795028
Hulu's Average Show Year: 2010.4947563232572
Prime Video's Average Show Year: 2009.773347897324
Disney+'s Average Show Year: 2012.2421652421651

# Based on my findings Netflix had the most recent shows with an average show year of 2016. This is followed by Disney+ with an average show year of 2012. Lastly, Prime Video with the oldest average show years of 2009. These could also reflect the showâ€™s likelihood to be on a platform based on the year they were produced.

In [25]:
# Which streaming platform caters more for kids age 7+?
netflix = tvshow[tvshow["Netflix"] == 1]
netflix_kid_age = netflix["Age"] == "7+"
netflix_showcount = 0
for age in netflix_kid_age:
    if age == True:
        netflix_showcount += 1

hulu = tvshow[tvshow["Hulu"] == 1]
hulu_kid_age = hulu["Age"] == "7+"
hulu_showcount = 0
for age in hulu_kid_age:
    if age == True:
        hulu_showcount += 1

primevideo = tvshow[tvshow["Prime Video"] == 1]
prime_video_kid_age = primevideo["Age"] == "7+"
prime_showcount = 0
for age in prime_video_kid_age:
    if age == True:
        prime_showcount += 1

disney = tvshow[tvshow["Disney+"] == 1]
disney_kid_age = disney["Age"] == "7+"
disney_showcount = 0
for age in disney_kid_age:
    if age == True:
        disney_showcount += 1

print("Netflix's kid friendy show count:", netflix_showcount,"\nHulu's kid friendy show count:", hulu_showcount,
      "\nPrime Video's kid friendy show count:", prime_showcount, "\nDisney+'s kid friendy show count:", disney_showcount)

Netflix's kid friendy show count: 299
Hulu's kid friendy show count: 325
Prime Video's kid friendy show count: 213
Disney+'s kid friendy show count: 109

# Through my analysis I found Hulu to have the most kid friendly shows at 325. Here kid friendly is defined as shows with an age 7+ rating. Following Hulu we have Netflix with 299 shows for kids. Lastly, Disney+ has the lowest show count for kids at 109.

In [24]:
# Which streaming platform has the most adult tv shows 18+?
netflix = tvshow[tvshow["Netflix"] == 1]
netflix_adult_age = netflix["Age"] == "18+"
netflix_showcount = 0
for age in netflix_adult_age:
    if age == True:
        netflix_showcount += 1

hulu = tvshow[tvshow["Hulu"] == 1]
hulu_adult_age = hulu["Age"] == "18+"
hulu_showcount = 0
for age in hulu_adult_age:
    if age == True:
        hulu_showcount += 1

primevideo = tvshow[tvshow["Prime Video"] == 1]
prime_video_adult_age = primevideo["Age"] == "18+"
prime_showcount = 0
for age in prime_video_adult_age:
    if age == True:
        prime_showcount += 1

disney = tvshow[tvshow["Disney+"] == 1]
disney_adult_age = disney["Age"] == "18+"
disney_showcount = 0
for age in disney_adult_age:
    if age == True:
        disney_showcount += 1

print("Netflix's adult show count:", netflix_showcount,"\nHulu's adult show count:", hulu_showcount,
      "\nPrime Video's adult show count:", prime_showcount, "\nDisney+'s adult show count:", disney_showcount)

Netflix's adult show count: 482
Hulu's adult show count: 261
Prime Video's adult show count: 164
Disney+'s adult show count: 2

# Through my findings I found that Netflix had the highest show count for adults at 482 shows. Here adult meant people ages 18+. Following Netflix, Hulu had 261 shows with an adult rating. Lastly, Disney+ had only 2 18+ rating shows. This reflects Netflix's catering towards adults and with a big gap between its competitors.